trigger:
  branches:
    include:
    - master
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: endjin-github

 
jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'

#  variables:
#    service_connection_nuget_org: $(Endjin_Service_Connection_NuGet_Org)
#    service_connection_github: $(Endjin_Service_Connection_GitHub)

  steps:
  # GitVersion doesn't work on build agenst without the global tools workaround step
  - template: templates/install.dotnet-global-tools.workaround.yml@recommended_practices
  - template: templates/install-and-run-gitversion.yml@recommended_practices

  - powershell: |
      Write-Host "##vso[task.setvariable variable=Endjin_IsPreRelease]$((-not ([string]::IsNullOrEmpty($Env:GITVERSION_PRERELEASETAG))))"
      Write-Host "##vso[task.setvariable variable=Endjin_Repository_Name]$Env:BUILD_REPOSITORY_NAME"
    displayName: 'Set Environment Variables'

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '5.4.0'

  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: 'src/Endjin.RecommendedPractices.NuGet/Endjin.RecommendedPractices.nuspec'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'GitVersion.SemVer'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Release Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'      
    condition: and(succeeded(), or(variables['Endjin.ForcePublish'], eq(variables['GitVersion.PreReleaseTag'], '')))
    inputs:
      gitHubConnection: endjin-github
      repositoryName: $(Endjin_Repository_Name)
      tagSource: manual
      tag: $(GitVersion.SemVer) 
      isPreRelease: $(Endjin_IsPreRelease)
      assets: |
          $(Build.ArtifactStagingDirectory)/**

# This will have to wait until Howard can set up a service connection to NuGet.org
#  - task: NuGetCommand@2
#    displayName: 'Publish to nuget.org'
#    condition: and(succeeded(), or(variables['Endjin.ForcePublish'], eq(variables['GitVersion.PreReleaseTag'], '')))
#    inputs:
#      command: push
#      nuGetFeedType: external
#      publishFeedCredentials: ${{ parameters.service_connection_nuget_org }}
#      versioningScheme: byBuildNumber
#      packagesToPush: '$(Build.ArtifactStagingDirectory)/Packages/**/*.nupkg'