trigger:
  branches:
    include:
    - master
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: endjin

 
jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'

#  variables:
#    service_connection_nuget_org: $(Endjin_Service_Connection_NuGet_Org)
#    service_connection_github: $(Endjin_Service_Connection_GitHub)

  steps:
  - template: templates/install.dotnet-global-tools.workaround.yml@recommended_practices
  - template: templates/install-and-run-gitversion.yml@recommended_practices
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '5.4.0'

  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: 'src/Endjin.RecommendedPractices.NuGet/Endjin.RecommendedPractices.nuspec'
      versioningScheme: 'byBuildNumber'